pipeline {
    agent any
       
       parameters{
        string(name: 'SPEC', defaultValue: "cypress/e2e/**/**", description: "Enter the scripts path that you want to execute")
        choice(name: 'BROWSER', choices: ['chrome','edge', 'firefox'], description: "choose the browser where you want to execute your tests")

       }

       options{
        ansiColor('xterm')
       }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
               bat "npm i"
               bat "npx cypress run --browser ${BROWSER} --spec ${SPEC}"
                
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }

       
    }

     post{
            always{
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'cypress/reports/html', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: 'TEST', useWrapperFileDirectly: true])
            }
        }
}